#include<iostream>
using namespace std;
main()
{
int number01;
int number02;
int number03;
int number04;
int number05;
int number06;
int number07;
int number08;
int number09;
int number10;
int number11;
int number12;
int number13;
int number14;
int number15;
int add;
int multiply;
int subtract;
int sum;
cout << "Enter 1st Number : ";
cin >> number01;
cout << "Enter 2nd Number : ";
cin >> number02;
cout << "Enter 3rd Number : ";
cin >> number03;
cout << "Enter 4th Number : ";
cin >> number04;
cout << "Enter 5th Number : ";
cin >> number05;
cout << "Enter 6th Number : ";
cin >> number06;
cout << "Enter 7th Number : ";
cin >> number07;
cout << "Enter 8th Number : ";
cin >> number08;
cout << "Enter 9th Number : ";
cin >> number09;
cout << "Enter 10th Number : ";
cin >> number10;
cout << "Enter 11th Number : ";
cin >> number11;
cout << "Enter 12th Number : ";
cin >> number12;
cout << "Enter 13th Number : ";
cin >> number13;
cout << "Enter 14th Number : ";
cin >> number14;
cout << "Enter 15th Number : ";
cin >> number15;
add = number01+number02+number03+number04+number05;
multiply = number06*number07*number08*number09*number10;
subtract =  number11-number12-number13-number14-number15;
sum = add+multiply-subtract;
cout << "Sum : " << sum; 
}